---
- name: "[RabbitMQ] Create users"
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    configure_priv: "{{ item.configure_priv | default(omit) }}"
    read_priv: "{{ item.read_priv | default(omit) }}"
    write_priv: "{{ item.write_priv | default(omit) }}"
    vhost: "{{ item.vhost | default(omit) }}"
    permissions: "{{ item.permissions | default(omit) }}"
    tags: "{{ item.tags | default(omit) }}"
    update_password: "{{ item.update_password | default(omit) }}"
  no_log: true
  with_items:
    - "{{ rabbitmq_users_to_create }}"
  when:
    - rabbitmq_is_master
      or rabbitmq_slave_of is none

- name: "[RabbitMQ] Delete unwanted users"
  rabbitmq_user:
    user: "{{ item }}"
    state: absent
  with_items:
    - "{{ rabbitmq_users_to_delete }}"
  when:
    - rabbitmq_is_master
      or rabbitmq_slave_of is none
