---
- hosts: rabbitmq-master rabbitmq-slave
  remote_user: molecule
  become: true
  any_errors_fatal: true
  tasks:
    - import_tasks: pre_tasks.yml
      vars:
        nb_master2check: 2
        nb_slave2check: 3
    - import_tasks: pre_tasks_ssl.yml

- hosts: rabbitmq-master
  remote_user: molecule
  become: true
  any_errors_fatal: true
  roles:
    - role: ansible-role-erlang
      vars:
        erlang_series: "{{ lookup('env','ERLANG_SERIES') }}"
    - role: ansible-role-rabbitmq
      vars:
        rabbitmq_series: "{{ lookup('env','RABBITMQ_SERIES') }}"

- hosts: rabbitmq-slave
  remote_user: molecule
  become: true
  any_errors_fatal: true
  roles:
    - role: ansible-role-erlang
      vars:
        erlang_series: "{{ lookup('env','ERLANG_SERIES') }}"
    - role: ansible-role-rabbitmq
      vars:
        rabbitmq_series: "{{ lookup('env','RABBITMQ_SERIES') }}"

- hosts: rabbitmq-master
  remote_user: molecule
  become: true
  any_errors_fatal: true
  tasks:
    - import_tasks: post_tasks_cluster.yml
    - import_tasks: post_tasks.yml
